import type { Metadata } from "next";
import { GlobalStyle } from "@/styles/globals";
import { saira } from "@/config/fonts";
import { Header } from "@/components/header";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

const RootLayout = ({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) => {
	return (
		<html lang="en" suppressHydrationWarning>
			<body className={`${saira.variable}`} suppressHydrationWarning>
				<Header />
				{children}
				<GlobalStyle />
			</body>
		</html>
	);
};

export default RootLayout;
