import type { Metadata } from "next";
import { saira } from "@/config/fonts";
import { Header } from "@/components/header";
import { Providers } from "@/components/providers";
import { ContentBase } from "@/styles/globals";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

const RootLayout = ({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) => {
	return (
		<html lang="en" suppressHydrationWarning>
			<body className={`${saira.variable}`} suppressHydrationWarning>
				<Providers>
					<ContentBase>
						<Header />
						{children}
					</ContentBase>
				</Providers>
			</body>
		</html>
	);
};

export default RootLayout;
